// source: hashring.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require("google-protobuf");
var goog = jspb;
var global = function () {
  if (this) {
    return this;
  }
  if (typeof window !== "undefined") {
    return window;
  }
  if (typeof global !== "undefined") {
    return global;
  }
  if (typeof self !== "undefined") {
    return self;
  }
  return Function("return this")();
}.call(null);

var google_protobuf_any_pb = require("google-protobuf/google/protobuf/any_pb.js");
goog.object.extend(proto, google_protobuf_any_pb);
goog.exportSymbol("proto.hashring.ErrorResponse", null, global);
goog.exportSymbol("proto.hashring.PeerPayload", null, global);
goog.exportSymbol("proto.hashring.PeerPayload.ResponseCase", null, global);
goog.exportSymbol("proto.hashring.StreamCommand", null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.hashring.StreamCommand = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.hashring.StreamCommand, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.hashring.StreamCommand.displayName = "proto.hashring.StreamCommand";
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.hashring.ErrorResponse = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.hashring.ErrorResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.hashring.ErrorResponse.displayName = "proto.hashring.ErrorResponse";
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.hashring.PeerPayload = function (opt_data) {
  jspb.Message.initialize(
    this,
    opt_data,
    0,
    -1,
    null,
    proto.hashring.PeerPayload.oneofGroups_,
  );
};
goog.inherits(proto.hashring.PeerPayload, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.hashring.PeerPayload.displayName = "proto.hashring.PeerPayload";
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.hashring.StreamCommand.prototype.toObject = function (
    opt_includeInstance,
  ) {
    return proto.hashring.StreamCommand.toObject(opt_includeInstance, this);
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.hashring.StreamCommand} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.hashring.StreamCommand.toObject = function (includeInstance, msg) {
    var f,
      obj = {
        namespace: jspb.Message.getFieldWithDefault(msg, 1, ""),
        command: jspb.Message.getFieldWithDefault(msg, 2, ""),
        key: jspb.Message.getFieldWithDefault(msg, 3, ""),
        payload: jspb.Message.getFieldWithDefault(msg, 4, ""),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.hashring.StreamCommand}
 */
proto.hashring.StreamCommand.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.hashring.StreamCommand();
  return proto.hashring.StreamCommand.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.hashring.StreamCommand} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.hashring.StreamCommand}
 */
proto.hashring.StreamCommand.deserializeBinaryFromReader = function (
  msg,
  reader,
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readString());
        msg.setNamespace(value);
        break;
      case 2:
        var value = /** @type {string} */ (reader.readString());
        msg.setCommand(value);
        break;
      case 3:
        var value = /** @type {string} */ (reader.readString());
        msg.setKey(value);
        break;
      case 4:
        var value = /** @type {string} */ (reader.readString());
        msg.setPayload(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.hashring.StreamCommand.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter();
  proto.hashring.StreamCommand.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.hashring.StreamCommand} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.hashring.StreamCommand.serializeBinaryToWriter = function (
  message,
  writer,
) {
  var f = undefined;
  f = message.getNamespace();
  if (f.length > 0) {
    writer.writeString(1, f);
  }
  f = message.getCommand();
  if (f.length > 0) {
    writer.writeString(2, f);
  }
  f = message.getKey();
  if (f.length > 0) {
    writer.writeString(3, f);
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeString(4, f);
  }
};

/**
 * optional string namespace = 1;
 * @return {string}
 */
proto.hashring.StreamCommand.prototype.getNamespace = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};

/**
 * @param {string} value
 * @return {!proto.hashring.StreamCommand} returns this
 */
proto.hashring.StreamCommand.prototype.setNamespace = function (value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};

/**
 * optional string command = 2;
 * @return {string}
 */
proto.hashring.StreamCommand.prototype.getCommand = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};

/**
 * @param {string} value
 * @return {!proto.hashring.StreamCommand} returns this
 */
proto.hashring.StreamCommand.prototype.setCommand = function (value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};

/**
 * optional string key = 3;
 * @return {string}
 */
proto.hashring.StreamCommand.prototype.getKey = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};

/**
 * @param {string} value
 * @return {!proto.hashring.StreamCommand} returns this
 */
proto.hashring.StreamCommand.prototype.setKey = function (value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};

/**
 * optional string payload = 4;
 * @return {string}
 */
proto.hashring.StreamCommand.prototype.getPayload = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};

/**
 * @param {string} value
 * @return {!proto.hashring.StreamCommand} returns this
 */
proto.hashring.StreamCommand.prototype.setPayload = function (value) {
  return jspb.Message.setField(this, 4, value);
};

/**
 * Clears the field making it undefined.
 * @return {!proto.hashring.StreamCommand} returns this
 */
proto.hashring.StreamCommand.prototype.clearPayload = function () {
  return jspb.Message.setField(this, 4, undefined);
};

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.hashring.StreamCommand.prototype.hasPayload = function () {
  return jspb.Message.getField(this, 4) != null;
};

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.hashring.ErrorResponse.prototype.toObject = function (
    opt_includeInstance,
  ) {
    return proto.hashring.ErrorResponse.toObject(opt_includeInstance, this);
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.hashring.ErrorResponse} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.hashring.ErrorResponse.toObject = function (includeInstance, msg) {
    var f,
      obj = {
        message: jspb.Message.getFieldWithDefault(msg, 1, ""),
        code: jspb.Message.getFieldWithDefault(msg, 2, ""),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.hashring.ErrorResponse}
 */
proto.hashring.ErrorResponse.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.hashring.ErrorResponse();
  return proto.hashring.ErrorResponse.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.hashring.ErrorResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.hashring.ErrorResponse}
 */
proto.hashring.ErrorResponse.deserializeBinaryFromReader = function (
  msg,
  reader,
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readString());
        msg.setMessage(value);
        break;
      case 2:
        var value = /** @type {string} */ (reader.readString());
        msg.setCode(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.hashring.ErrorResponse.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter();
  proto.hashring.ErrorResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.hashring.ErrorResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.hashring.ErrorResponse.serializeBinaryToWriter = function (
  message,
  writer,
) {
  var f = undefined;
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(1, f);
  }
  f = message.getCode();
  if (f.length > 0) {
    writer.writeString(2, f);
  }
};

/**
 * optional string message = 1;
 * @return {string}
 */
proto.hashring.ErrorResponse.prototype.getMessage = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};

/**
 * @param {string} value
 * @return {!proto.hashring.ErrorResponse} returns this
 */
proto.hashring.ErrorResponse.prototype.setMessage = function (value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};

/**
 * optional string code = 2;
 * @return {string}
 */
proto.hashring.ErrorResponse.prototype.getCode = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};

/**
 * @param {string} value
 * @return {!proto.hashring.ErrorResponse} returns this
 */
proto.hashring.ErrorResponse.prototype.setCode = function (value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.hashring.PeerPayload.oneofGroups_ = [[1, 2]];

/**
 * @enum {number}
 */
proto.hashring.PeerPayload.ResponseCase = {
  RESPONSE_NOT_SET: 0,
  COMMAND: 1,
  ERROR: 2,
};

/**
 * @return {proto.hashring.PeerPayload.ResponseCase}
 */
proto.hashring.PeerPayload.prototype.getResponseCase = function () {
  return /** @type {proto.hashring.PeerPayload.ResponseCase} */ (
    jspb.Message.computeOneofCase(
      this,
      proto.hashring.PeerPayload.oneofGroups_[0],
    )
  );
};

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.hashring.PeerPayload.prototype.toObject = function (
    opt_includeInstance,
  ) {
    return proto.hashring.PeerPayload.toObject(opt_includeInstance, this);
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.hashring.PeerPayload} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.hashring.PeerPayload.toObject = function (includeInstance, msg) {
    var f,
      obj = {
        command:
          (f = msg.getCommand()) &&
          proto.hashring.StreamCommand.toObject(includeInstance, f),
        error:
          (f = msg.getError()) &&
          proto.hashring.ErrorResponse.toObject(includeInstance, f),
        id: jspb.Message.getFieldWithDefault(msg, 3, ""),
        ip: jspb.Message.getFieldWithDefault(msg, 4, ""),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.hashring.PeerPayload}
 */
proto.hashring.PeerPayload.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.hashring.PeerPayload();
  return proto.hashring.PeerPayload.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.hashring.PeerPayload} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.hashring.PeerPayload}
 */
proto.hashring.PeerPayload.deserializeBinaryFromReader = function (
  msg,
  reader,
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = new proto.hashring.StreamCommand();
        reader.readMessage(
          value,
          proto.hashring.StreamCommand.deserializeBinaryFromReader,
        );
        msg.setCommand(value);
        break;
      case 2:
        var value = new proto.hashring.ErrorResponse();
        reader.readMessage(
          value,
          proto.hashring.ErrorResponse.deserializeBinaryFromReader,
        );
        msg.setError(value);
        break;
      case 3:
        var value = /** @type {string} */ (reader.readString());
        msg.setId(value);
        break;
      case 4:
        var value = /** @type {string} */ (reader.readString());
        msg.setIp(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.hashring.PeerPayload.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter();
  proto.hashring.PeerPayload.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.hashring.PeerPayload} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.hashring.PeerPayload.serializeBinaryToWriter = function (
  message,
  writer,
) {
  var f = undefined;
  f = message.getCommand();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.hashring.StreamCommand.serializeBinaryToWriter,
    );
  }
  f = message.getError();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.hashring.ErrorResponse.serializeBinaryToWriter,
    );
  }
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(3, f);
  }
  f = message.getIp();
  if (f.length > 0) {
    writer.writeString(4, f);
  }
};

/**
 * optional StreamCommand command = 1;
 * @return {?proto.hashring.StreamCommand}
 */
proto.hashring.PeerPayload.prototype.getCommand = function () {
  return /** @type{?proto.hashring.StreamCommand} */ (
    jspb.Message.getWrapperField(this, proto.hashring.StreamCommand, 1)
  );
};

/**
 * @param {?proto.hashring.StreamCommand|undefined} value
 * @return {!proto.hashring.PeerPayload} returns this
 */
proto.hashring.PeerPayload.prototype.setCommand = function (value) {
  return jspb.Message.setOneofWrapperField(
    this,
    1,
    proto.hashring.PeerPayload.oneofGroups_[0],
    value,
  );
};

/**
 * Clears the message field making it undefined.
 * @return {!proto.hashring.PeerPayload} returns this
 */
proto.hashring.PeerPayload.prototype.clearCommand = function () {
  return this.setCommand(undefined);
};

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.hashring.PeerPayload.prototype.hasCommand = function () {
  return jspb.Message.getField(this, 1) != null;
};

/**
 * optional ErrorResponse error = 2;
 * @return {?proto.hashring.ErrorResponse}
 */
proto.hashring.PeerPayload.prototype.getError = function () {
  return /** @type{?proto.hashring.ErrorResponse} */ (
    jspb.Message.getWrapperField(this, proto.hashring.ErrorResponse, 2)
  );
};

/**
 * @param {?proto.hashring.ErrorResponse|undefined} value
 * @return {!proto.hashring.PeerPayload} returns this
 */
proto.hashring.PeerPayload.prototype.setError = function (value) {
  return jspb.Message.setOneofWrapperField(
    this,
    2,
    proto.hashring.PeerPayload.oneofGroups_[0],
    value,
  );
};

/**
 * Clears the message field making it undefined.
 * @return {!proto.hashring.PeerPayload} returns this
 */
proto.hashring.PeerPayload.prototype.clearError = function () {
  return this.setError(undefined);
};

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.hashring.PeerPayload.prototype.hasError = function () {
  return jspb.Message.getField(this, 2) != null;
};

/**
 * optional string id = 3;
 * @return {string}
 */
proto.hashring.PeerPayload.prototype.getId = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};

/**
 * @param {string} value
 * @return {!proto.hashring.PeerPayload} returns this
 */
proto.hashring.PeerPayload.prototype.setId = function (value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};

/**
 * optional string ip = 4;
 * @return {string}
 */
proto.hashring.PeerPayload.prototype.getIp = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};

/**
 * @param {string} value
 * @return {!proto.hashring.PeerPayload} returns this
 */
proto.hashring.PeerPayload.prototype.setIp = function (value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};

goog.object.extend(exports, proto.hashring);
